### PR TITLE
📦: µhtml website; articles generator

### PR DESCRIPTION
**Pull request by hypervillain**
https://deploy-preview-4--netlify-plugin-search-index.netlify.app/

Goal: provide people with a fully working example.

**website**
I'm rebuilding the website by providing an actual search bar.
It uses [µhtml](https://github.com/WebReflection/uhtml) because I just discovered it and it seems awesome 👍

**articles**
It comes with a bunch of articles fetched from [newsapi](https://newsapi.org), transformed to HTML
and a `generator.js` file that can regenerate these articles whenever needed.

Todo:
- [ ] about section
- [ ] Github links

### CODE REVIEW

**Comment by swyxio** [comment]
damn thats a lot of articles haha. sure you want to check this in? i think i'm ok with it, a bit worried that the fixtures are volatile and cause a lot of commit noise

**Comment by hypervillain** [comment]
haha right 🙈I'll generate them at build time

**Comment by hypervillain** [comment]
@sw-yx you need to add a `NEWS_API_KEY` env variable to your Netlify site and trigger a rebuild.
I'll send you mine on Twitter

**Comment by swyxio** [comment]
much better

**Pull request merged**
